### ISSUE TITLE
Pycurl problem

### ISSUE THREAD

**Issue by eporedieis** [SaWey/home-assistant-dahua-event#1]
Hello, I follow your instructions but I have a problem. I have HA version 0.65.4 and pycurl (installed manually) version 7.43.0.1.
Starting HA, it appears these errors:

- **Error loading custom_components.dahua_event. Make sure all dependencies are installed**

> Error loading custom_components.dahua_event. Make sure all dependencies are installed
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 142, in get_component
>     module = importlib.import_module(path)
>   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 673, in exec_module
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
>   File "/home/homeassistant/.homeassistant/custom_components/dahua_event.py", line 10, in <module>
>     import threading, logging, os, socket, pycurl, time
> ImportError: No module named 'pycurl'`

- **Unable to find component dahua_event**

- **Setup failed for dahua_event: Component not found.**

What could I do to use pycurl - that it's installed - into HA?

**Comment by eporedieis** [comment]
Solutions for any other users [is here](https://community.home-assistant.io/t/how-to-install-working-pycurl-needed-for-a-component/48590/2).
